project:
  type: book
  output-dir: docs

book:
  title: "paneldesc package guides"
  author: Dmitrii Tereshchenko
  chapters:
    - index.qmd
    - 00_start.qmd
    - 01_basic.qmd
    - 02_panel.qmd
    - 03_extend.qmd
    - 04_processing.qmd
    - 05_Stata.qmd
    - 06_comparison.qmd


format:
  html:
    theme: cosmo
    df-print: kable
    toc: true

editor: source

